name: Suggestion
description: Help us improve with suggestions
labels: ["Type: Suggestion :bulb:"]
assignees: mcanouil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: suggestion
    attributes:
      label: Link to suggested blog
      description: Please share a link to your suggested blog
      placeholder: https://...
    validations:
      required: true
  - type: dropdown
    id: fos
    validations:
      required: true
    attributes:
      label: Targeted field of science (OECD)
      description: Please select the field of science you wish your blog suggestion to appear in.
      multiple: false
      options:
        - Natural sciences
        - Mathematics
        - Computer and information sciences
        - Physical sciences
        - Chemical sciences
        - Earth and related environmental sciences
        - Biological sciences
        - Other natural sciences
        - Engineering and technology
        - Civil engineeering
        - Electrical engineering, electronic engineering, information engineering
        - Mechanical engineering
        - Chemical engineering
        - Materials engineering
        - Medical engineering
        - Environmental engineering
        - Environmental biotechnology
        - Industrial biotechnology
        - Nano technology
        - Other engineering and technologies
        - Medical and health sciences
        - Basic medicine
        - Clinical medicine
        - Health sciences
        - Health biotechnology
        - Other medical sciences
        - Agricultural sciences
        - Agriculture, forestry, and fisheries
        - Animal and dairy science
        - Veterinary science
        - Agricultural biotechnology
        - Other agricultural sciences
        - Social science
        - Psychology
        - Economics and business
        - Educational sciences
        - Sociology
        - Law
        - Political science
        - Social and economic geography
        - Media and communications
        - Other social sciences
        - Humanities
        - History and archaeology
        - Languages and literature
        - Philosophy, ethics and religion
        - Arts (arts, history of arts, performing arts, music)
        - Other humanities
  - type: checkboxes
    id: Checklist
    attributes:
      label: Checklist
      description: |
        When filing a _suggestion_, please check the boxes below to confirm that you have:
      options:
        - label: checked that your suggestion is not already listed in __Awesome science blogs__ list.
          required: true
        - label: checked when if the blog is actively publishing (at least one post in the past 12 months).
          required: true
